  - name: pr-${repo}-linuxelfbuild-${lin_version}-${win_version}-${build_type}
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job ${repo}/job/linuxelfbuild --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER,TEST_INFRA=false,BUILD_TYPE=${build_type},BUILD_MODE=${build_mode},WINDOWS_VERSION=${win_version},LINUX_VERSION=${lin_version}"
