presubmits:
  openenclave/openenclave-mbedtls:
  - name: pr-openenclave-mbedtls-ubuntu-1604
    branches:
    - openenclave-mbedtls-2.16
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu-1604:latest
        command:
        - /bin/bash
        args:
        - -c
        - "/testing/openenclave-mbedtls/make-build.sh"

  - name: pr-openenclave-mbedtls-ubuntu-1804
    branches:
    - openenclave-mbedtls-2.16
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu-1804:latest
        command:
        - /bin/bash
        args:
        - -c
        - "/testing/openenclave-mbedtls/make-build.sh"

  - name: pr-openenclave-mbedtls-jenkins-ping
    branches:
    - openenclave-mbedtls-2.16
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job test-infra/job/jenkins-ping --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN"

  - name: pr-test-infra-ping
    branches:
    - openenclave-mbedtls-2.16
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/jenkinsoperator:latest
        command:
        - /bin/bash
        args:
        - -c
        - "echo ping"

#  - name: pr-openenclave-mbedtls-rhel8-clang-8
#    branches:
#    - openenclave-mbedtls-2.16
#    always_run: true
#    decorate: true
#    skip_report: false
#    max_concurrency: 10
#    spec:
#      containers:
#        - image: openenclave/jenkinsoperator:latest
#          command:
#            - sh
#            - "-c"
#            - "python /hack/jenkins_bootstrap.py --job openenclave-mbedtls/job/Rhel8Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER,TEST_INFRA=false,BUILD_TYPE=Release"
