periodics:
  - name: ci-openenclave-mbedtls-ubuntu-1604
    extra_refs:
    - org: openenclave
      repo: openenclave-mbedtls
      base_ref: openenclave-mbedtls-2.16
    decorate: true
    interval: 6h4m
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - "-c"
            - "/testing/openenclave-mbedtls/make-build.sh"

  - name: ci-openenclave-mbedtls-ubuntu-1804
    extra_refs:
    - org: openenclave
      repo: openenclave-mbedtls
      base_ref: openenclave-mbedtls-2.16
    decorate: true
    interval: 6h4m
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - "-c"
            - "/testing/openenclave-mbedtls/make-build.sh"

#  - name: ci-openenclave-mbedtls-rhel-8
#    extra_refs:
#    - org: openenclave
#      repo: openenclave-mbedtls
#      base_ref: openenclave-mbedtls-2.16
#    decorate: true
#    interval: 6h4m
#    spec:
#      containers:
#        - image: openenclave/jenkinsoperator:latest
#          command:
#            - sh
#            - "-c"
#            - "python /hack/jenkins_bootstrap.py --job openenclave-mbedtls/job/Rhel8Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=openenclave-mbedtls-2.16,TEST_INFRA=false,BUILD_TYPE=Debug"
