build-configs:
  pre-submits
  periodics
  postsubmits

repos:
  oeedger8r-cpp
  openenclave

oeedger8r-cpp:
  operating-systems:
    ubuntu1604
    ubuntu1804

  build-modes:
    simulation

  build-types:
    Release
    Debug

  compilers:
    clang-8
    clang-7
    gcc

openenclave:
  operating-systems:
    ubuntu1604
    ubuntu1804

  build-modes:
    simulation
    hardware

  build-types:
    Release
    RelWithDebInfo 
    Debug

  compilers:
    clang-8
    clang-7
    gcc
