presubmits:
  openenclave/oeedger8r-cpp:
  - name: pr-openenclave-oeedger8r-cmake-1804
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu1804:latest
        command:
        - /bin/bash
        args:
        - -c
        - "/hack/cmake-build.sh"
  - name: pr-openenclave-oeedger8-cmake-1604
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu1604:latest
        command:
        - /bin/bash
        args:
        - -c
        - "/hack/cmake-build.sh"
  - name: pr-openenclave-test-infra-ping
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/test-infra:latest
        command:
        - /bin/bash
        args:
        - -c
        - "echo ping"