postsubmits:
  openenclave/oeedger8r-cpp:
  - name: post-oeedger8r-cpp-ubuntu-1604-Release-clang-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/testing/oeedger8r-cpp/cmake-build.sh -b=Release --compiler=clang-8'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: post-oeedger8r-cpp-ubuntu-1604-Release-clang-7
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/testing/oeedger8r-cpp/cmake-build.sh -b=Release --compiler=clang-7'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: post-oeedger8r-cpp-ubuntu-1604-Release-gcc
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/testing/oeedger8r-cpp/cmake-build.sh -b=Release --compiler=gcc'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: post-oeedger8r-cpp-ubuntu-1604-Debug-clang-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/testing/oeedger8r-cpp/cmake-build.sh -b=Debug --compiler=clang-8'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: post-oeedger8r-cpp-ubuntu-1604-Debug-clang-7
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/testing/oeedger8r-cpp/cmake-build.sh -b=Debug --compiler=clang-7'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: post-oeedger8r-cpp-ubuntu-1604-Debug-gcc
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/testing/oeedger8r-cpp/cmake-build.sh -b=Debug --compiler=gcc'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: post-oeedger8r-cpp-ubuntu-1804-Release-clang-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/testing/oeedger8r-cpp/cmake-build.sh -b=Release --compiler=clang-8'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: post-oeedger8r-cpp-ubuntu-1804-Release-clang-7
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/testing/oeedger8r-cpp/cmake-build.sh -b=Release --compiler=clang-7'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: post-oeedger8r-cpp-ubuntu-1804-Release-gcc
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/testing/oeedger8r-cpp/cmake-build.sh -b=Release --compiler=gcc'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: post-oeedger8r-cpp-ubuntu-1804-Debug-clang-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/testing/oeedger8r-cpp/cmake-build.sh -b=Debug --compiler=clang-8'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: post-oeedger8r-cpp-ubuntu-1804-Debug-clang-7
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/testing/oeedger8r-cpp/cmake-build.sh -b=Debug --compiler=clang-7'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: post-oeedger8r-cpp-ubuntu-1804-Debug-gcc
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/testing/oeedger8r-cpp/cmake-build.sh -b=Debug --compiler=gcc'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock        

  - name: ci-oeedger8r-cpp-rhel8-clang-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job oeedger8r-cpp/job/Rhel8Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters 'PULL_NUMBER=master,REPO_NAME=oeedger8r-cpp,REPO_OWNER=openenclave'"

  - name: ci-oeedger8r-cpp-windows-2016
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job oeedger8r-cpp/job/Windows2016Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters 'PULL_NUMBER=master,REPO_NAME=oeedger8r-cpp,REPO_OWNER=openenclave'"

  - name: ci-oeedger8r-cpp-windows-2019
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job oeedger8r-cpp/job/Windows2019Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters 'PULL_NUMBER=master,REPO_NAME=oeedger8r-cpp,REPO_OWNER=openenclave'"
