periodics:
  - name: ci-openenclave-oeedger8r-cmake-1804
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 3m
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
            - sh
            - "-c"
            - "/hack/cmake-build.sh"