presubmits:
  openenclave-ci/oeedger8r-cpp:
  - name: pr-oeedger8r-1804
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu1804:latest
        command:
        - /bin/bash
        args:
        - -c
        - "/hack/cmake-build.sh"