periodics:
  - name: ci-oeedger8r-cpp-ubuntu-1604-Release-clang-8
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - "-c"
            - "/testing/oeedger8r-cpp/cmake-build.sh -b=Release --compiler=clang-8"

  - name: ci-oeedger8r-cpp-ubuntu-1604-Release-clang-7
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - "-c"
            - "/testing/oeedger8r-cpp/cmake-build.sh -b=Release --compiler=clang-7"

  - name: ci-oeedger8r-cpp-ubuntu-1604-Release-gcc
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - "-c"
            - "/testing/oeedger8r-cpp/cmake-build.sh -b=Release --compiler=gcc"

  - name: ci-oeedger8r-cpp-ubuntu-1604-Debug-clang-8
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - "-c"
            - "/testing/oeedger8r-cpp/cmake-build.sh -b=Debug --compiler=clang-8"

  - name: ci-oeedger8r-cpp-ubuntu-1604-Debug-clang-7
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - "-c"
            - "/testing/oeedger8r-cpp/cmake-build.sh -b=Debug --compiler=clang-7"

  - name: ci-oeedger8r-cpp-ubuntu-1604-Debug-gcc
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - "-c"
            - "/testing/oeedger8r-cpp/cmake-build.sh -b=Debug --compiler=gcc"

  - name: ci-oeedger8r-cpp-ubuntu-1804-Release-clang-8
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - "-c"
            - "/testing/oeedger8r-cpp/cmake-build.sh -b=Release --compiler=clang-8"

  - name: ci-oeedger8r-cpp-ubuntu-1804-Release-clang-7
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - "-c"
            - "/testing/oeedger8r-cpp/cmake-build.sh -b=Release --compiler=clang-7"

  - name: ci-oeedger8r-cpp-ubuntu-1804-Release-gcc
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - "-c"
            - "/testing/oeedger8r-cpp/cmake-build.sh -b=Release --compiler=gcc"

  - name: ci-oeedger8r-cpp-ubuntu-1804-Debug-clang-8
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - "-c"
            - "/testing/oeedger8r-cpp/cmake-build.sh -b=Debug --compiler=clang-8"

  - name: ci-oeedger8r-cpp-ubuntu-1804-Debug-clang-7
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - "-c"
            - "/testing/oeedger8r-cpp/cmake-build.sh -b=Debug --compiler=clang-7"

  - name: ci-oeedger8r-cpp-ubuntu-1804-Debug-gcc
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - "-c"
            - "/testing/oeedger8r-cpp/cmake-build.sh -b=Debug --compiler=gcc"        

  - name: ci-oeedger8r-cpp-rhel8-clang-8
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 12h1m
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job oeedger8r-cpp/job/Rhel8Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters LL_NUMBER=master,TEST_INFRA=false"

  - name: ci-oeedger8r-cpp-windows-2016
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 12h1m
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job oeedger8r-cpp/job/Windows2016Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters LL_NUMBER=master,TEST_INFRA=false"

  - name: ci-oeedger8r-cpp-windows-2019
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 12h1m
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job oeedger8r-cpp/job/Windows2019Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=master,TEST_INFRA=false"
