
periodics:
- name: periodic-openenclave-oeedger8r-1804-dry
  decorate: true
  interval: 12h
  spec:
    containers:
    - image: brmclare/oesdk-ubuntu1804-dev:latest
      command:
      - sh
      - "-c"
      # Hack, need to get Docker file in oeeger8r repo
      - "git clone --recursive https://github.com/openenclave-ci/oeedger8r-cpp && cd oeedger8r-cpp && \
      mkdir build && \
      cd build && \
      cmake .. && \
      make && \
      ctest"

- name: periodic-openenclave-oeedger8r-1804-full
  decorate: true
  interval: 12h
  spec:
    containers:
    - image: brmclare/oesdk-ubuntu1804-dev:latest
      command:
      - sh
      - "-c"
      # Hack, need to get Docker file in oeeger8r repo
      - "git clone --recursive https://github.com/openenclave-ci/oeedger8r-cpp && cd oeedger8r-cpp && \
      mkdir build && \
      cd build && \
      cmake .. && \
      make && \
      ctest"

- name: periodic-openenclave-oeedger8r-1604-dry
  decorate: true
  interval: 12h
  spec:
    containers:
    - image: brmclare/oesdk-ubuntu1604-dev:latest
      command:
      - sh
      - "-c"
      # Hack, need to get Docker file in oeeger8r repo
      - "git clone --recursive https://github.com/openenclave-ci/oeedger8r-cpp && cd oeedger8r-cpp && \
      mkdir build && \
      cd build && \
      cmake .. && \
      make"

- name: periodic-openenclave-oeedger8r-1604-full
  decorate: true
  interval: 12h
  spec:
    containers:
    - image: brmclare/oesdk-ubuntu1604-dev:latest
      command:
      - sh
      - "-c"
      # Hack, need to get Docker file in oeeger8r repo
      - "git clone --recursive https://github.com/openenclave-ci/oeedger8r-cpp && cd oeedger8r-cpp && \
      mkdir build && \
      cd build && \
      cmake .. && \
      make && \
      ctest"