presubmits:
  openenclave/oeedger8r-cpp:
  - name: pr-oeedger8r-cpp-ubuntu-1604-Release-clang-8
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu-1604:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/testing/oeedger8r-cpp/cmake-build.sh -b=Release --compiler=clang-8'

  - name: pr-oeedger8r-cpp-ubuntu-1604-Release-clang-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu-1604:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/testing/oeedger8r-cpp/cmake-build.sh -b=Release --compiler=clang-7'

  - name: pr-oeedger8r-cpp-ubuntu-1604-Release-gcc
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu-1604:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/testing/oeedger8r-cpp/cmake-build.sh -b=Release --compiler=gcc'

  - name: pr-oeedger8r-cpp-ubuntu-1604-Debug-clang-8
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu-1604:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/testing/oeedger8r-cpp/cmake-build.sh -b=Debug --compiler=clang-8'

  - name: pr-oeedger8r-cpp-ubuntu-1604-Debug-clang-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu-1604:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/testing/oeedger8r-cpp/cmake-build.sh -b=Debug --compiler=clang-7'

  - name: pr-oeedger8r-cpp-ubuntu-1604-Debug-gcc
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu-1604:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/testing/oeedger8r-cpp/cmake-build.sh -b=Debug --compiler=gcc'

  - name: pr-oeedger8r-cpp-ubuntu-1804-Release-clang-8
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu-1804:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/testing/oeedger8r-cpp/cmake-build.sh -b=Release --compiler=clang-8'

  - name: pr-oeedger8r-cpp-ubuntu-1804-Release-clang-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu-1804:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/testing/oeedger8r-cpp/cmake-build.sh -b=Release --compiler=clang-7'

  - name: pr-oeedger8r-cpp-ubuntu-1804-Release-gcc
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu-1804:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/testing/oeedger8r-cpp/cmake-build.sh -b=Release --compiler=gcc'

  - name: pr-oeedger8r-cpp-ubuntu-1804-Debug-clang-8
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu-1804:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/testing/oeedger8r-cpp/cmake-build.sh -b=Debug --compiler=clang-8'

  - name: pr-oeedger8r-cpp-ubuntu-1804-Debug-clang-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu-1804:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/testing/oeedger8r-cpp/cmake-build.sh -b=Debug --compiler=clang-7'

  - name: pr-oeedger8r-cpp-ubuntu-1804-Debug-gcc
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu-1804:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/testing/oeedger8r-cpp/cmake-build.sh -b=Debug --compiler=gcc'        

  - name: pr-oeedger8r-cpp-jenkins-ping
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job job-runner --jenkins-user $(echo $JENKINS_USER) --url $(echo $JENKINS_URL) --jenkins-password $(echo $JENKINS_TOKEN)"

  - name: pr-oeedger8r-cpp-rhel8-clang-8
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job oeedger8r-cpp/job/Rhel8Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER,REPO_NAME=oeedger8r-cpp,REPO_OWNER=openenclave"

  - name: pr-oeedger8r-cpp-windows-2016
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job oeedger8r-cpp/job/Windows2016Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER,REPO_NAME=oeedger8r-cpp,REPO_OWNER=openenclave"

  - name: pr-oeedger8r-cpp-windows-2019
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job oeedger8r-cpp/job/Windows2019Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER,REPO_NAME=oeedger8r-cpp,REPO_OWNER=openenclave"
