prowjob_namespace: default
pod_namespace: test-pods
log_level: debug
tide:
  sync_period: 2m
  queries:
    - repos:
        - BRMcLaren/test-infra
      labels:
        - lgtm
        - approved
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebases
plank:
  job_url_prefix_config:
    '*': http://oe-prow-status.uksouth.cloudapp.azure.com/view/gcs
  job_url_template: 'http://oe-prow-status.uksouth.cloudapp.azure.com/view/gcs/oe-prow-artifacts/pr-logs/pull/{{.Spec.Refs.Repo}}/{{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}/{{.Spec.Job}}/{{.Status.BuildID}}'
  report_templates:
    '*': '[Full PR test history](http://oe-prow-status.uksouth.cloudapp.azure.com/pr-history?org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}). [Your PR dashboard](http://oe-prow-status.uksouth.cloudapp.azure.com/pr?query=is%3Apr%20state%3Aopen%20author%3{{with index .Spec.Refs.Pulls 0}}{{.Author}}{{end}}). Please help us cut down on flakes by openening an issue when you hit one in your PR.'
  pod_pending_timeout: 15m
  pod_unscheduled_timeout: 1m
  default_decoration_configs:
    '*':
      timeout: 4h
      grace_period: 10m
      utility_images:
        clonerefs: "gcr.io/k8s-prow/clonerefs:v20200710-7fa016752a"
        initupload: "gcr.io/k8s-prow/initupload:v20200710-7fa016752a"
        entrypoint: "gcr.io/k8s-prow/entrypoint:v20200710-7fa016752a"
        sidecar: "gcr.io/k8s-prow/sidecar:v20200710-7fa016752a"
      gcs_configuration:
        bucket: oe-prow-artifacts
        path_strategy: explicit
      gcs_credentials_secret: gcs-credentials
github_reporter:
  job_types_to_report:
    - presubmit
    - postsubmit
sinker:
  resync_period: 15m
  max_prowjob_age: 6h
  max_pod_age: 48h
  terminated_pod_ttl: 30m
presubmits:
  BRMcLaren/test-infra:
  - name: pr-test-infra-ping
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/test-infra:latest
        command:
        - /bin/bash
        args:
        - -c
        - "echo ping"

  - name: pr-test-infra-validate-cmake-build
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu1804:latest
        command:
        - /bin/bash
        args:
        - -c
        - "git clone https://github.com/openenclave/oeedger8r-cpp && cd oeedger8r-cpp && /hack/cmake-build.sh"

  - name: pr-test-infra-validate-prow-job-config
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/test-infra:latest
        command:
        - /bin/bash
        args:
        - -c
        - "./hack/merge-prow-jobs.sh && ./hack/validate-prow-jobs.sh"
periodics:
  - name: ci-openenclave-test-infra-validate-test-infra-image-1604
    extra_refs:
    - org: BRMcLaren
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: brmclare/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "docker build . -f images/debian/1604/Dockerfile"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: ci-openenclave-test-infra-validate-test-infra-image-1804
    extra_refs:
    - org: BRMcLaren
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: brmclare/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "docker build . -f images/debian/1804/Dockerfile"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
