prowjob_namespace: default
pod_namespace: test-pods
tide:
  target_url: http://oe-prow-status.uksouth.cloudapp.azure.com/tide
  pr_status_base_url: http://oe-prow-status.uksouth.cloudapp.azure.com/view/gcs/oe-prow-artifacts/pr-logs/pull/{{.Spec.Refs.Repo}}/{{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}/{{.Spec.Job}}/{{.Status.BuildID}}
  sync_period: 1m
  queries:
    - repos:
        - BRMcLaren/test-infra
      labels:
        - lgtm
        - approved
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebases
plank:
  default_decoration_configs:
    '*':
      utility_images: # using the tag we identified above
        clonerefs: "gcr.io/k8s-prow/clonerefs:v20191108-08fbf64ac"
        initupload: "gcr.io/k8s-prow/initupload:v20191108-08fbf64ac"
        entrypoint: "gcr.io/k8s-prow/entrypoint:v20191108-08fbf64ac"
        sidecar: "gcr.io/k8s-prow/sidecar:v20191108-08fbf64ac"
      gcs_configuration:
        bucket: oe-prow-artifacts # the bucket we just made
        path_strategy: explicit
      gcs_credentials_secret: gcs-credentials # the secret we just made
github_reporter:
  job_types_to_report:
    - presubmit
    - postsubmit
sinker:
  resync_period: 15m
  max_prowjob_age: 48h
  max_pod_age: 48h
  terminated_pod_ttl: 30m
presubmits:
  BRMcLaren/test-infra:
    - name: pull-test-infra-latest
      branches:
        - master
      always_run: true
      decorate: true
      skip_report: false
      max_concurrency: 10
      spec:
        containers:
          - image: openenclave/test-infra:latest
            command:
              - /bin/bash
            args:
              - -c
              - "echo ping"
  openenclave-ci/oeedger8r-cpp:
    - name: pull-oeedger8r-1804
      branches:
        - master
      always_run: true
      decorate: true
      skip_report: false
      max_concurrency: 10
      spec:
        containers:
          - image: brmclare/oesdk-ubuntu1804-dev:latest
            command:
              - /bin/bash
            args:
              - -c
              - "./hack/checkout.sh && ./hack/cmakebuild.sh"
    - name: pull-oeedger8r-1604
      branches:
        - master
      always_run: true
      decorate: true
      skip_report: false
      max_concurrency: 10
      spec:
        containers:
          - image: brmclare/oesdk-ubuntu1604-dev:latest
            command:
              - /bin/bash
            args:
              - -c
              - "./hack/checkout.sh && ./hack/cmakebuild.sh"
periodics:
  - name: periodic-openenclave-openenclave-sdk-1604-dry
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: brmclare/oesdk-ubuntu1604-dev:latest
          command:
            - sh
            - "-c"
            # Hack, need to get Docker file in oeeger8r repo
            - "git clone --recursive https://github.com/openenclave/openenclave && cd openenclave && mkdir build && cd build && cmake .. && make"
  - name: periodic-openenclave-openenclave-sdk-1604-full
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: brmclare/oesdk-ubuntu1604-dev:latest
          command:
            - sh
            - "-c"
            # Hack, need to get Docker file in oeeger8r repo
            - "git clone --recursive https://github.com/openenclave/openenclave && cd openenclave && mkdir build && cd build && cmake .. && make && OE_SIMULATION=1 ctest"
  - name: periodic-openenclave-openenclave-sdk-1804-dry
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: brmclare/oesdk-ubuntu1804-dev:latest
          command:
            - sh
            - "-c"
            # Hack, need to get Docker file in oeeger8r repo
            - "git clone --recursive https://github.com/openenclave/openenclave && cd openenclave && mkdir build && cd build && cmake .. && make"
  - name: periodic-openenclave-openenclave-sdk-1804-full
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: brmclare/oesdk-ubuntu1804-dev:latest
          command:
            - sh
            - "-c"
            # Hack, need to get Docker file in oeeger8r repo
            - "git clone --recursive https://github.com/openenclave/openenclave && cd openenclave && mkdir build && cd build && cmake .. && make && OE_SIMULATION=1 ctest"
  - name: periodic-openenclave-openenclave-1604-sdk-sgx-1
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: brmclare/oesdk-ubuntu1604-dev:latest
          command:
            - sh
            - "-c"
            # Hack, need to get Docker file in oeeger8r repo
            - "git clone --recursive https://github.com/openenclave/openenclave && cd openenclave && mkdir build && cd build && cmake .. && make && ctest"
          securityContext:
            privileged: true
      volumes:
        - name: dev-sgx
          hostPath:
            path: /dev/sgx
      restartPolicy: Never
  - name: periodic-openenclave-openenclave-1804-sdk-sgx-1
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: brmclare/oesdk-ubuntu1804-dev:latest
          command:
            - sh
            - "-c"
            # Hack, need to get Docker file in oeeger8r repo
            - "git clone --recursive https://github.com/openenclave/openenclave && cd openenclave && mkdir build && cd build && cmake .. && make && ctest"
          volumeMounts:
            - mountPath: /dev/sgx
              name: dev-sgx
          securityContext:
            privileged: true
      volumes:
        - name: dev-sgx
          hostPath:
            path: /dev/sgx
