# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
    - releases/*

jobs:
- job: docker_image_build
  displayName: Build and Push Prow Controller Image To Dogfood repo
  pool: 1804CISGXagentspool
  workspace:
    clean: all 
  steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'brmclareDockerHub'
        repository: 'brmclare/test-infra'
        command: 'buildAndPush'
        Dockerfile: 'config/prow/Dockerfile'
        buildContext: '.'
        tags: |
          $(Build.BuildId)

- job: docker_image_validate
  displayName: Validate Prow Controller Image  from Dogfood repo
  dependsOn: docker_image_build
  pool: 1804CISGXagentspool
  container: 
    image: brmclare/test-infra:$(Build.BuildId)
  steps:
    - script: 'git clone https://github.com/kubernetes/test-infra.git prow-tools; cd prow-tools && bazel-3.0.0 run //prow/cmd/checkconfig -- --plugin-config=$PWD/../config/prow/plugins.yaml --config-path=$PWD/../config/prow/config.yaml'