---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: ing
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  backend: # specify the default backend for `ingress-gce` (https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#default_backend)
    serviceName: deck
    servicePort: 80
  tls:
  - hosts:
    - oe-prow-status.uksouth.cloudapp.azure.com
    secretName: tls-secret
  rules:
  - host: oe-prow-status.uksouth.cloudapp.azure.com
    http:
      paths:
      - path: /
        backend:
          serviceName: deck
          servicePort: 80
      - path: /hook
        backend:
          serviceName: hook
          servicePort: 8888
