---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-operator
spec:
  replicas: 1 # Do not scale up.
  template:
    metadata:
      labels:
        app: jenkins-operator
    spec:
      containers:
      - name: jenkins-operator
        image: gcr.io/k8s-prow/jenkins-operator:latest
        ports:
        - name: logs
          containerPort: 8080
        args:
        - --dry-run=false
        - --config-path=/etc/config/config.yaml
        - --deck-url=http://oe-prow-status.uksouth.cloudapp.azure.com
        - --github-token-path=/etc/github/oauth
        - --jenkins-url=https://oe-prow-testing.uksouth.cloudapp.azure.com
        - --jenkins-token-file=/etc/jenkins/jenkins-token
        - --github-endpoint=http://ghproxy
        - --github-endpoint=https://api.github.com
        - --csrf-protect=true
        volumeMounts:
        - name: jenkins
          mountPath: /etc/jenkins
          readOnly: true
        - name: oauth
          mountPath: /etc/github
          readOnly: true
        - name: config
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: jenkins
        secret:
          secretName: jenkins-token
      - name: oauth
        secret:
          secretName: oauth-token
      - name: config
        configMap:
          name: config
  selector:
    matchLabels:
      app: jenkins-operator