---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: ingress-basic
  name: tls-ing
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - oe-prow-status.uksouth.cloudapp.azure.com
    secretName: tls-secret
  rules:
  - host: oe-prow-status.uksouth.cloudapp.azure.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: deck
          servicePort: 80
      - path: /deck
        backend:
          serviceName: deck
          servicePort: 80
      - path: /hook
        backend:
          serviceName: hook
          servicePort: 8888