  - name: ci-${repo}-${rhel_version}-${build_type}-clang-8
    extra_refs:
    - org: openenclave
      repo: ${repo}
      base_ref: master
    decorate: true
    interval: 1h${i}m
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job ${repo}/job/Rhel8Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=master,TEST_INFRA=false,BUILD_TYPE=${build_type}"
