periodics:
  - name: ci-openenclave-test-infra-validate-build-image-ubuntu-1604
    extra_refs:
    - org: openenclave-ci
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/ubuntu/1604/Dockerfile --docker_tag openenclave/ubuntu-1604:latest --docker_push --docker_user $DOCKER_USER --docker_pass $DOCKER_PASSWORD"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
            - mountPath: /dev/sgx
              name: dev-sgx
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never

  - name: ci-openenclave-test-infra-validate-build-image-ubuntu-1804
    extra_refs:
    - org: openenclave-ci
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/ubuntu/1804/Dockerfile --docker_tag openenclave/ubuntu-1804:latest --docker_push --docker_user $DOCKER_USER --docker_pass $DOCKER_PASSWORD"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
            - mountPath: /dev/sgx
              name: dev-sgx
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never

  - name: ci-openenclave-test-infra-validate-build-image-rhel-8.1
    extra_refs:
    - org: openenclave-ci
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/rhel/8.1/Dockerfile --skip_testing --docker_tag openenclave/rhel-8.1:latest --docker_push --docker_user $DOCKER_USER --docker_pass $DOCKER_PASSWORD"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: ci-openenclave-test-infra-validate-build-image-bootstrap-did
    extra_refs:
    - org: openenclave-ci
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/bootstap/Dockerfile --skip_testing --docker_tag openenclave/test-infra-did:latest --docker_push --docker_user $DOCKER_USER --docker_pass $DOCKER_PASSWORD"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: ci-openenclave-test-infra-validate-build-image-centos-7.5
    extra_refs:
    - org: openenclave-ci
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/centos/7.5/Dockerfile --skip_testing --docker_tag openenclave/centos-7.5:latest --docker_push --docker_user $DOCKER_USER --docker_pass $DOCKER_PASSWORD"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: ci-openenclave-test-infra-validate-build-image-fedora-31
    extra_refs:
    - org: openenclave-ci
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/fedora/31/Dockerfile --skip_testing --docker_tag openenclave/fedora-31:latest --docker_push --docker_user $DOCKER_USER --docker_pass $DOCKER_PASSWORD"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: ci-openenclave-test-infra-jenkins-ping
    extra_refs:
    - org: openenclave-ci
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job test-infra/job/jenkins-ping --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN"

  - name: ci-openenclave-test-infra-validate-build-image-windows-2019
    extra_refs:
    - org: openenclave-ci
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job test-infra/job/Windows2019DockerBuild --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=2"

  - name: ci-openenclave-test-infra-validate-oeedgrg8r-rhel-8
    extra_refs:
    - org: openenclave-ci
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job test-infra/job/oeedger8r-cpp/job/Rhel8Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=2,TEST_INFRA=true"

  - name: ci-openenclave-test-infra-validate-oeedgrg8r-win-2016
    extra_refs:
    - org: openenclave-ci
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job test-infra/job/oeedger8r-cpp/job/Windows2016Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=2,TEST_INFRA=true"

  - name: ci-openenclave-test-infra-validate-oeedgrg8r-win-2019
    extra_refs:
    - org: openenclave-ci
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job test-infra/job/oeedger8r-cpp/job/Windows2019Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=2,TEST_INFRA=true"
