periodics:
  - name: ci-openenclave-test-validate-prow-jobs
    extra_refs:
    - org: BRMcLaren
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 1h
    spec:
      containers:
        - image: openenclave/test-infra:latest
          command:
            - sh
            - "-c"
            - ./hack/merge-prow-jobs.sh && ./hack/validate-prow-jobs.sh""