presubmits:
  BRMcLaren/test-infra:
  - name: pull-test-infra-latest
    branches:
    - master
    always_run: true
    decorate: false
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/test-infralatest
        command:
        - /bin/bash
        args:
        - -c
        - "Echo ping"