periodics:
  - name: ci-openenclave-test-infra-validate-prow-jobs
    extra_refs:
    - org: BRMcLaren
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/test-infra:latest
          command:
            - sh
            - "-c"
            - "./hack/merge-prow-jobs.sh && ./hack/validate-prow-jobs.sh"

  - name: ci-openenclave-test-infra-validate-build-image-ubuntu-1604
    extra_refs:
    - org: BRMcLaren
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/ubuntu/1604/Dockerfile"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: ci-openenclave-test-infra-validate-build-image-ubuntu-1804
    extra_refs:
    - org: BRMcLaren
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/ubuntu/1804/Dockerfile"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: ci-openenclave-test-infra-validate-build-image-rhel-8.1
    extra_refs:
    - org: BRMcLaren
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/rhel/8.1/Dockerfile --skip_testing"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: ci-openenclave-test-infra-validate-build-image-bootstrap-did
    extra_refs:
    - org: BRMcLaren
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "docker build . -f images/bootstap/Dockerfile"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: ci-openenclave-test-infra-validate-build-image-centos-7.5
    extra_refs:
    - org: BRMcLaren
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/centos/7.5/Dockerfile --skip_testing"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: ci-openenclave-test-infra-validate-build-image-fedora-31
    extra_refs:
    - org: BRMcLaren
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/fedora/31/Dockerfile --skip_testing"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
