presubmits:
  openenclave-ci/test-infra:
  - name: pr-openenclave-test-infra-ping
    branches:
    - master
    run_if_changed: "images/*"
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/test-infra:latest
        command:
        - /bin/bash
        args:
        - -c
        - "echo ping"

  - name: pr-openenclave-test-infra-validate-cmake-build
    branches:
    - master
    run_if_changed: "images/*"
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu1804:latest
        command:
        - /bin/bash
        args:
        - -c
        - "git clone https://github.com/openenclave/oeedger8r-cpp && cd oeedger8r-cpp && /hack/cmake-build.sh"

  - name: pr-openenclave-test-infra-validate-build-image-ubuntu-1804
    branches:
    - master
    run_if_changed: "images/*"
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/ubuntu/1804/Dockerfile --docker_tag openenclave/ubuntu-1804"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: pr-openenclave-test-infra-validate-build-image-ubuntu-1604
    branches:
    - master
    run_if_changed: "images/*"
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/ubuntu/1804/Dockerfile --docker_tag openenclave/ubuntu-1604"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: pr-openenclave-test-infra-validate-build-image-bootstrap-did
    branches:
    - master
    run_if_changed: "images/*"
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "docker build . -f images/bootstap/Dockerfile"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: pr-openenclave-test-infra-validate-build-image-rhel-8.1
    branches:
    - master
    run_if_changed: "images/*"
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/rhel/8.1/Dockerfile --skip_testing --docker_tag openenclave/rhel-8.1"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: pr-openenclave-test-infra-validate-build-image-centos-7.5
    branches:
    - master
    run_if_changed: "images/*"
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/centos/7.5/Dockerfile --skip_testing --docker_tag centos-7.5"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: pr-openenclave-test-infra-validate-build-image-fedora-31
    branches:
    - master
    run_if_changed: "images/*"
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/fedora/31/Dockerfile --skip_testing --docker_tag fedora-31"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
