postsubmits:
  BRMcLaren/test-infra:
  - name: post-openenclave-test-infra-push-image-bootstrap-did
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "docker build . -f images/bootstap/Dockerfile"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: post-openenclave-test-infra-push-build-image-debian-1604
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/debian/1604/Dockerfile"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: post-openenclave-test-infra-push-build-image-debian-1804
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/debian/1804/Dockerfile"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: post-openenclave-test-infra-push-build-image-rhel-8.1
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/rhel/8.1/Dockerfile --skip_testing"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: post-openenclave-test-infra-push-build-image-centos-7.5
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/centos/7.5/Dockerfile --skip_testing"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
