  - name: ci-${org}-${repo}-jenk-${operating_system}-${build_type_short}-${compiler_short}
    extra_refs:
    - org: ${org}
      repo: ${repo}
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - '-c'
            - 'echo "I am not implemented yet! Thanks for your interest in this project!"'