  - name: post-${org}-${repo}-jenk-${operating_system}-${build_type_short}-${compiler_short}
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - '-c'
            - 'echo "I am not implemented yet! Thanks for your interest in this project!"'
