build-configs:
  pre-submits
  periodics
  postsubmits

repos:
  openenclave

openenclave:
  prowjob-operating-systems:
    ubuntu1604
    ubuntu1804
  win-operating-systems:
    2016
    2019
  rhel-operating-systems:
    8.1

  build-modes:
    simulation
    hardware

  build-types-win:
    Release 
    Debug
  build-types-lin:
    Release
    RelWithDebInfo
    Debug

  compilers:
    clang-8
    clang-7
    gcc
