periodics:

  - name: ci-openenclave-ci-openenclave-ubuntu1604-Release-c-8
    extra_refs:
    - org: openenclave-ci
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=clang-8'        

  - name: ci-openenclave-ci-openenclave-ubuntu1604-Release-gcc
    extra_refs:
    - org: openenclave-ci
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=gcc'        

  - name: ci-openenclave-ci-openenclave-ubuntu1604-RelWithDebInfo-c-8
    extra_refs:
    - org: openenclave-ci
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=clang-8'        

  - name: ci-openenclave-ci-openenclave-ubuntu1604-RelWithDebInfo-gcc
    extra_refs:
    - org: openenclave-ci
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=gcc'        

  - name: ci-openenclave-ci-openenclave-ubuntu1604-Debug-c-8
    extra_refs:
    - org: openenclave-ci
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=clang-8'        

  - name: ci-openenclave-ci-openenclave-ubuntu1604-Debug-gcc
    extra_refs:
    - org: openenclave-ci
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=gcc'        

  - name: ci-openenclave-ci-openenclave-acc-ubuntu1604-Release-c-8
    extra_refs:
    - org: openenclave-ci
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=clang-8'
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never        

  - name: ci-openenclave-ci-openenclave-acc-ubuntu1604-Release-gcc
    extra_refs:
    - org: openenclave-ci
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=gcc'
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never        

  - name: ci-openenclave-ci-openenclave-acc-ubuntu1604-RelWithDebInfo-c-8
    extra_refs:
    - org: openenclave-ci
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=clang-8'
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never        

  - name: ci-openenclave-ci-openenclave-acc-ubuntu1604-RelWithDebInfo-gcc
    extra_refs:
    - org: openenclave-ci
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=gcc'
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never        

  - name: ci-openenclave-ci-openenclave-acc-ubuntu1604-Debug-c-8
    extra_refs:
    - org: openenclave-ci
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=clang-8'
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never        

  - name: ci-openenclave-ci-openenclave-acc-ubuntu1604-Debug-gcc
    extra_refs:
    - org: openenclave-ci
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=gcc'
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never        

  - name: ci-openenclave-ci-openenclave-ubuntu1804-Release-c-8
    extra_refs:
    - org: openenclave-ci
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=clang-8'        

  - name: ci-openenclave-ci-openenclave-ubuntu1804-Release-gcc
    extra_refs:
    - org: openenclave-ci
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=gcc'        

  - name: ci-openenclave-ci-openenclave-ubuntu1804-RelWithDebInfo-c-8
    extra_refs:
    - org: openenclave-ci
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=clang-8'        

  - name: ci-openenclave-ci-openenclave-ubuntu1804-RelWithDebInfo-gcc
    extra_refs:
    - org: openenclave-ci
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=gcc'        

  - name: ci-openenclave-ci-openenclave-ubuntu1804-Debug-c-8
    extra_refs:
    - org: openenclave-ci
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=clang-8'        

  - name: ci-openenclave-ci-openenclave-ubuntu1804-Debug-gcc
    extra_refs:
    - org: openenclave-ci
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=gcc'        

  - name: ci-openenclave-ci-openenclave-acc-ubuntu1804-Release-c-8
    extra_refs:
    - org: openenclave-ci
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=clang-8'
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never        

  - name: ci-openenclave-ci-openenclave-acc-ubuntu1804-Release-gcc
    extra_refs:
    - org: openenclave-ci
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=gcc'
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never        

  - name: ci-openenclave-ci-openenclave-acc-ubuntu1804-RelWithDebInfo-c-8
    extra_refs:
    - org: openenclave-ci
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=clang-8'
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never        

  - name: ci-openenclave-ci-openenclave-acc-ubuntu1804-RelWithDebInfo-gcc
    extra_refs:
    - org: openenclave-ci
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=gcc'
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never        

  - name: ci-openenclave-ci-openenclave-acc-ubuntu1804-Debug-c-8
    extra_refs:
    - org: openenclave-ci
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=clang-8'
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never        

  - name: ci-openenclave-ci-openenclave-acc-ubuntu1804-Debug-gcc
    extra_refs:
    - org: openenclave-ci
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=gcc'
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never        
