presubmits:
  openenclave-ci/openenclave:

  - name: pr-openenclave-ci-openenclave-ubuntu1604-Release-c-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu1604:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Release --compiler=c-7'        

  - name: pr-openenclave-ci-openenclave-ubuntu1604-Release-gcc
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu1604:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Release --compiler=gcc'        

  - name: pr-openenclave-ci-openenclave-ubuntu1604-RelWithDebInfo-c-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu1604:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=c-7'        

  - name: pr-openenclave-ci-openenclave-ubuntu1604-RelWithDebInfo-gcc
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu1604:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=gcc'        

  - name: pr-openenclave-ci-openenclave-ubuntu1604-Debug-c-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu1604:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Debug --compiler=c-7'        

  - name: pr-openenclave-ci-openenclave-ubuntu1604-Debug-gcc
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu1604:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Debug --compiler=gcc'        

  - name: pr-openenclave-ci-openenclave-acc-ubuntu1604-Release-c-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
          - /bin/bash
          args:
          - -c
          - '/hack/cmake-build.sh -b=Release --compiler=c-7'
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never        

  - name: pr-openenclave-ci-openenclave-acc-ubuntu1604-Release-gcc
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
          - /bin/bash
          args:
          - -c
          - '/hack/cmake-build.sh -b=Release --compiler=gcc'
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never        

  - name: pr-openenclave-ci-openenclave-acc-ubuntu1604-RelWithDebInfo-c-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
          - /bin/bash
          args:
          - -c
          - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=c-7'
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never        

  - name: pr-openenclave-ci-openenclave-acc-ubuntu1604-RelWithDebInfo-gcc
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
          - /bin/bash
          args:
          - -c
          - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=gcc'
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never        

  - name: pr-openenclave-ci-openenclave-acc-ubuntu1604-Debug-c-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
          - /bin/bash
          args:
          - -c
          - '/hack/cmake-build.sh -b=Debug --compiler=c-7'
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never        

  - name: pr-openenclave-ci-openenclave-acc-ubuntu1604-Debug-gcc
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
          - /bin/bash
          args:
          - -c
          - '/hack/cmake-build.sh -b=Debug --compiler=gcc'
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never        

  - name: pr-openenclave-ci-openenclave-ubuntu1804-Release-c-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu1804:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Release --compiler=c-7'        

  - name: pr-openenclave-ci-openenclave-ubuntu1804-Release-gcc
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu1804:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Release --compiler=gcc'        

  - name: pr-openenclave-ci-openenclave-ubuntu1804-RelWithDebInfo-c-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu1804:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=c-7'        

  - name: pr-openenclave-ci-openenclave-ubuntu1804-RelWithDebInfo-gcc
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu1804:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=gcc'        

  - name: pr-openenclave-ci-openenclave-ubuntu1804-Debug-c-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu1804:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Debug --compiler=c-7'        

  - name: pr-openenclave-ci-openenclave-ubuntu1804-Debug-gcc
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu1804:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Debug --compiler=gcc'        

  - name: pr-openenclave-ci-openenclave-acc-ubuntu1804-Release-c-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
          - /bin/bash
          args:
          - -c
          - '/hack/cmake-build.sh -b=Release --compiler=c-7'
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never        

  - name: pr-openenclave-ci-openenclave-acc-ubuntu1804-Release-gcc
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
          - /bin/bash
          args:
          - -c
          - '/hack/cmake-build.sh -b=Release --compiler=gcc'
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never        

  - name: pr-openenclave-ci-openenclave-acc-ubuntu1804-RelWithDebInfo-c-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
          - /bin/bash
          args:
          - -c
          - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=c-7'
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never        

  - name: pr-openenclave-ci-openenclave-acc-ubuntu1804-RelWithDebInfo-gcc
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
          - /bin/bash
          args:
          - -c
          - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=gcc'
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never        

  - name: pr-openenclave-ci-openenclave-acc-ubuntu1804-Debug-c-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
          - /bin/bash
          args:
          - -c
          - '/hack/cmake-build.sh -b=Debug --compiler=c-7'
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never        

  - name: pr-openenclave-ci-openenclave-acc-ubuntu1804-Debug-gcc
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
          - /bin/bash
          args:
          - -c
          - '/hack/cmake-build.sh -b=Debug --compiler=gcc'
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never        
