  - name: ci-${repo}-sim-${operating_system}-${build_type}-${compiler}
    extra_refs:
    - org: ${org}
      repo: ${repo}
      base_ref: master
    decorate: true
    interval: 1h${i}m
    spec:
      containers:
        - image: openenclave/${operating_system}:latest
          command:
            - sh
            - '-c'
            - '/testing/openenclave/cmake-build.sh -b=${build_type} --compiler=${compiler}'
