periodics:

  - name: ci-openenclave-oeedger8r-cmake-1604-Release-clang-7
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=clang-7'

  - name: ci-openenclave-oeedger8r-cmake-1604-Release-gcc
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=gcc'

  - name: ci-openenclave-oeedger8r-cmake-1604-Debug-clang-7
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=clang-7'

  - name: ci-openenclave-oeedger8r-cmake-1604-Debug-gcc
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=gcc'

  - name: ci-openenclave-oeedger8r-cmake-1604-RelWithDebInfo-clang-7
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=clang-7'

  - name: ci-openenclave-oeedger8r-cmake-1604-RelWithDebInfo-gcc
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=gcc'

  - name: ci-openenclave-oeedger8r-cmake-1804-Release-clang-7
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=clang-7'

  - name: ci-openenclave-oeedger8r-cmake-1804-Release-gcc
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=gcc'

  - name: ci-openenclave-oeedger8r-cmake-1804-Debug-clang-7
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=clang-7'

  - name: ci-openenclave-oeedger8r-cmake-1804-Debug-gcc
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=gcc'

  - name: ci-openenclave-oeedger8r-cmake-1804-RelWithDebInfo-clang-7
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=clang-7'

  - name: ci-openenclave-oeedger8r-cmake-1804-RelWithDebInfo-gcc
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=gcc'
