# Image build and validate e2e

trigger:
  branches:
    include:
    - master
    - releases/*

jobs:
- job: docker_push_oe_ci_linux
  displayName: Docker Build and Push CI Images for Openenclave
  strategy:
    matrix:
      Ubuntu_1804:
        DockerFile_Path: images/debian/1804/Dockerfile
        repository: brmclare/oesdk-ubuntu1804-dogfood
        pool: 1804CISGXagentspool
      Ubuntu_1604:
        DockerFile_Path: images/debian/1804/Dockerfile
        repository: brmclare/oesdk-ubuntu1604-dogfood
        pool: 1804CISGXagentspool
      #Windows_2019:
        #DockerFile_Path: images/windows/2019/Dockerfile
        #repository: brmclare/oesdk-windows2019-dogfood
    maxParallel: 99
  pool:
      name: $(pool)
  workspace:
    clean: all 
  #container: containerReference # container to run this job inside
  timeoutInMinutes: 60
  steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'brmclareDockerHub'
        repository: '$(repository)'
        command: 'buildAndPush'
        Dockerfile: '$(DockerFile_Path)'
        buildContext: '.'
        tags: |
          $(Build.BuildId)