presubmits:
  openenclave/openenclave-curl:
  - name: pr-openenclave-curl-ubuntu-1604
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - "-c"
            - "/testing/openenclave-curl/make-build.sh"
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never
  - name: pr-openenclave-curl-ubuntu-1804
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - "-c"
            - "/testing/openenclave-curl/make-build.sh"
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never

  - name: pr-openenclave-curl-jenkins-ping
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job test-infra/job/jenkins-ping --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN"

  - name: pr-test-infra-ping
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/jenkinsoperator:latest
        command:
        - /bin/bash
        args:
        - -c
        - "echo ping"

#  - name: pr-openenclave-curl-rhel8-clang-8
#    branches:
#    - openenclave-curl
#    always_run: true
#    decorate: true
#    skip_report: false
#    max_concurrency: 10
#    spec:
#      containers:
#        - image: openenclave/jenkinsoperator:latest
#          command:
#            - sh
#            - "-c"
#            - "python /hack/jenkins_bootstrap.py --job openenclave-curl/job/Rhel8Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER,TEST_INFRA=false,BUILD_TYPE=Release"
