postsubmits:
  openenclave/openenclave-curl:
  - name: post-openenclave-curl-ubuntu-1604
    branches:
    - openenclave-curl
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - "-c"
            - "/testing/openenclave-curl/make-build.sh"
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never

  - name: post-openenclave-curl-ubuntu-1804
    branches:
    - openenclave-curl
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - "-c"
            - "/testing/openenclave-curl/make-build.sh"
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never

# - name: post-openenclave-curl-rhel-8
#    branches:
#    - openenclave-curl
#    decorate: true
#    spec:
#      containers:
#        - image: openenclave/jenkinsoperator:latest
#          command:
#            - sh
#            - "-c"
#            - "python /hack/jenkins_bootstrap.py --job openenclave-curl/job/Rhel8Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=openenclave-curl,TEST_INFRA=false,BUILD_TYPE=Debug"
