presubmits:
  openenclave/openenclave-curl:
  - name: pr-openenclave-curl-jenkins-ping
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job test-infra/job/jenkins-ping --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN"

  - name: pr-test-infra-ping
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/jenkinsoperator:latest
        command:
        - /bin/bash
        args:
        - -c
        - "echo ping"
