periodics:
  - name: ci-openenclave-openenclave-cmake-1804
    extra_refs:
    - org: openenclave
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 3h
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
            - sh
            - "-c"
            - "/hack/cmake-build.sh"

  - name: ci-openenclave-openenclave-cmake-1604
    extra_refs:
    - org: openenclave
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 3h
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
            - sh
            - "-c"
            - "/hack/cmake-build.sh"
