periodics:
- name: periodic-openenclave-openenclave-sdk-1804-1234
  extra_refs:
  - org: openenclave
    repo: openenclave
  decorate: true 
  interval: 12h
  spec:
    containers:
    - image: openenclave/ubuntu1804:latest
      command:
      - sh
      - "-c"
      # Hack, need to get Docker file in oeeger8r repo
      - "echo ping"
      securityContext:
        privileged: true
    volumes:
    - name: dev-sgx
      hostPath:
        path: /dev/sgx
    restartPolicy: Never