periodics:
  - name: ci-openenclave-openenclave-cmake-1804-2
    extra_refs:
    - org: openenclave
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 5m
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
            - sh
            - "-c"
            - "/hack/cmake-build.sh"
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never

  - name: ci-openenclave-openenclave-cmake-1604-2
    extra_refs:
    - org: openenclave
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 5m
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
            - sh
            - "-c"
            - "/hack/cmake-build.sh"
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never
